### ISSUE TITLE
Purescript Example

### ISSUE THREAD

**Issue by MikeBild** [CodeCommission/dropstack-examples#14]

**Comment by CarstenKoenig** [comment]
gonna try to give you a PR in the same manner as the elm example for this - is this ok?

**Comment by MikeBild** [comment]
Yep! 👍

**Comment by CarstenKoenig** [comment]
can you have a look at this: https://github.com/CodeCommission/dropstack-examples/tree/purescript-demo/purescript-example ? (not sure if it will work like this - it should install purescript/pulp/bower via yarn/npm then fetch react and react-dom, install the purescript dependencies via bower, compile the pux example and use it in index.html)

**Comment by MikeBild** [comment]
Great stuff! I'll try it ASAP.

BTW: It's possible to run it locally. Just install [docker](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/) on you machine, go into purescript-example folder and enter:

`docker build -t purescript-example .`
`docker run -it -p 8080:80 purescript-example`

open 192.169.99.100:8080 in your browser or use `curl 192.169.99.100:8080`

**Comment by CarstenKoenig** [comment]
cool ... will try - I think there is a install script from here: https://get.docker.com/ - is this safe or did you install docker via package manager or something similar?

**Comment by CarstenKoenig** [comment]
I think I have docker setup and ready to go ... and yep there where a lot of issues in my dockerfile ... busily fixing right now ...

**Comment by CarstenKoenig** [comment]
ok ... I got - it works on my local machine (see fixes in https://github.com/CodeCommission/dropstack-examples/commit/46056e0bfafa8df511bd4804e9a55350d17a4b8f)

some remarks:

- it complaints (warns) about yarn being installed via yarn (???)
- yarn does not like to install bower (AFAIK purescript still recommends bower though) - should I use npm to install it instead?
- are you fine with those warnings?

**Comment by MikeBild** [comment]
Cool! I did some small modifications to fix the issues (b7133dfebc8af91fb338b907fb4d5bb51d34317e). That should be deployable.

**Comment by CarstenKoenig** [comment]
To be honest I don't know right now what the story with bower/purescript is right now but last time I checked this was the reasoning: http://harry.garrood.me/blog/purescript-why-bower/

I think there where plans to switch to something different but right now it's still in the official recommendations (https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md) that's why I use it as is (yeah I'm basically ignorant of all the npm VS yarn, gulp VS bower, Webpack, etc. stuff - I think I'll need a really long workshop for this sometime)

the rest I just *copied*  from your Elm example ;) - so thanks for pointing out that stuff - helps me a lot

---

PS: I guess with "send a PR" you want me to do it ... so I just do :D

**Comment by MikeBild** [comment]
JS stuff ... sometimes ... weird... wherever -> ship it -> 4d87d9ceea38ff091dc7b06448aa0d3845c9a9d4
